### PR TITLE
Rely more on standards and other small adjustments

### PR DESCRIPTION
**Pull request by alexpovel**
Hi!

Thanks for putting this together, neat little tool.

This PR is about a bunch of things, most of which are one-line changes. Submitting a PR *each* would have felt silly---let me know if this works for you.

A changelog would be:

- Rely on ISO8601 for `date` formatting. I think this is a no-brainer, *but* maybe less portable. I had previously tried `--iso-8601` but switched to `-I`, which Alpine/Busybox can also do.
- There was an unused variable, `$checkfile`. I put it to use where it was probably intended to
- `ping` command existence wasn't previously checked for, so just quickly add that
- `checks.list` is a table, so we can use CSV formatting, a standard everyone is familiar with: still a text file, but can now be opened and edited in LibreOffice Calc and edited there, for example. Further, `.csv` is a suffix people will instantly know what to do with ("Oh I guess data goes here, and I know in which format it's needed"). CSV is even rendered nicely by GitHub itself, although the file is missing a header row:

    csv

- I'm planning on using this script as a Docker `healthcheck`: run this temporarily and generate a status page. However, the healthcheck instruction itself relies on the healthcheck process' exit code. Exiting the script with a failure code when the HTML page is also in "failed" status let's us hook this script into the Docker ecosystem, and Docker can signal unhealthiness from it now. This is then useful for countless other things and tools (email notifications, ...).

Let me know if you like any of the propositions.

### CODE REVIEW

**Comment by alexpovel** [comment]
Oh woops I'm working on this right now too, I won't push my rebased changes then.

**Comment by bderenzo** [comment]
Thanks for your PR. I agree with all the points except from error code in case of failed verification. If the script was executed without error with failed checks it should return 0. I understand your point, I think this could be a parameter in the script, I'm thinking about the best way to implement it.

**Comment by alexpovel** [comment]
The option could be like `curl`:

```bash
$ curl --fail --silent www.google.com/dummy || echo $?
22
```

**Comment by bderenzo** [comment]
@alexpovel I implement the failure exit code on failed check. It should be enabled in the beginning of the script: `failonoutage=true`. When enabled the error code is the number of failed checks. Does it suit to your needs ?

**Comment by alexpovel** [comment]
Yeah that works, thanks. I looked into parsing CLI options in bash, but in the spirit of *tiny*status that's probably overkill.

**Pull request merged**
